//
// Created by lucas on 28/11/2021.
//

#pragma once

#define __fn_ServerNetworkHandler_displayGameMessage "_ZN20ServerNetworkHandler19_displayGameMessageERK6PlayerR9ChatEvent"
#define __fn_Level_onPlayerDeath "_ZN5Level13onPlayerDeathER6PlayerRK17ActorDamageSource"
#define __fn_ServerNetworkHandler_handle_PlayerAuthInputPacketName "_ZN20ServerNetworkHandler6handleERK17NetworkIdentifierRK21PlayerAuthInputPacket"
#define __fn_ActorDamageSource_lookupCause "_ZN17ActorDamageSource15lookupCauseNameB5cxx11E16ActorDamageCause"
#define __fn_ActorDamageSource_getCause "_ZNK17ActorDamageSource8getCauseEv"
#define __fn_NetworkIdentifier_getHash "_ZNK17NetworkIdentifier7getHashEv"
#define __fn_ConnectionRequest_getData "_ZNK17ConnectionRequest7getDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"
#define __fn_ServerNetworkHandler_onClientAuthenticated "_ZN20ServerNetworkHandler22_onClientAuthenticatedERK17NetworkIdentifierRK11Certificate"
#define __fn_ExtendedCertificate_getIdentityName "_ZN19ExtendedCertificate15getIdentityNameB5cxx11ERK11Certificate"
#define __fn_ExtendedCertificate_getXuid "_ZN19ExtendedCertificate7getXuidB5cxx11ERK11Certificate"
#define __fn_ServerNetworkHandler_onPlayerLeft "_ZN20ServerNetworkHandler13_onPlayerLeftEP12ServerPlayerb"
#define __fn_ServerNetworkHandler_onTick "_ZN20ServerNetworkHandler6onTickEv"
#define __fn_TextPacket_createChat "_ZN10TextPacket10createChatERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_TextPacket "_ZN10TextPacketC1Ev"
#define __fn_TextPacket_destructor "_ZN10TextPacketD1Ev"