//
// Created by lucas on 28/11/2021.
//

#pragma once

#define __fn_ServerNetworkHandler_displayGameMessage "_ZN20ServerNetworkHandler19_displayGameMessageERK6PlayerR9ChatEvent"
#define __fn_Level_onPlayerDeath "_ZN5Level13onPlayerDeathER6PlayerRK17ActorDamageSource"
#define __fn_ServerNetworkHandler_handle_PlayerAuthInputPacketName "_ZN20ServerNetworkHandler6handleERK17NetworkIdentifierRK21PlayerAuthInputPacket"
#define __fn_ActorDamageSource_lookupCause "_ZN17ActorDamageSource15lookupCauseNameB5cxx11E16ActorDamageCause"
#define __fn_ActorDamageSource_getCause "_ZNK17ActorDamageSource8getCauseEv"
#define __fn_NetworkIdentifier_getHash "_ZNK17NetworkIdentifier7getHashEv"
#define __fn_ConnectionRequest_getData "_ZNK17ConnectionRequest7getDataERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"
#define __fn_ServerNetworkHandler_onClientAuthenticated "_ZN20ServerNetworkHandler22_onClientAuthenticatedERK17NetworkIdentifierRK11Certificate"
#define __fn_ExtendedCertificate_getIdentityName "_ZN19ExtendedCertificate15getIdentityNameB5cxx11ERK11Certificate"
#define __fn_ExtendedCertificate_getXuid "_ZN19ExtendedCertificate7getXuidB5cxx11ERK11Certificate"
#define __fn_ServerNetworkHandler_onPlayerLeft "_ZN20ServerNetworkHandler13_onPlayerLeftEP12ServerPlayerb"
#define __fn_ServerNetworkHandler_onTick "_ZN20ServerNetworkHandler6onTickEv"

#define __fn_TextPacket_createChat "_ZN10TextPacket10createChatERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_createRaw "_ZN10TextPacket9createRawERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"
#define __fn_TextPacket_createTranslated "_ZN10TextPacket16createTranslatedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS5_SaIS5_EE"
#define __fn_TextPacket_createTranslatedChat "_ZN10TextPacket20createTranslatedChatERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_createSystemMessage "_ZN10TextPacket19createSystemMessageERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"
#define __fn_TextPacket_createTextObjectWhisperMessage "_ZN10TextPacket30createTextObjectWhisperMessageERK18ResolvedTextObjectRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_"
#define __fn_TextPacket_createJukeboxPopup "_ZN10TextPacket18createJukeboxPopupERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS5_SaIS5_EE"
#define __fn_TextPacket_createAnnouncement "_ZN10TextPacket18createAnnouncementERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_createTranslatedAnnouncement "_ZN10TextPacket28createTranslatedAnnouncementERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_createTextObjectMessage "_ZN10TextPacket23createTextObjectMessageERK18ResolvedTextObjectNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_"
#define __fn_TextPacket_createWhisper "_ZN10TextPacket13createWhisperERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_S7_"
#define __fn_TextPacket_TextPacket "_ZN10TextPacketC1Ev"
#define __fn_TextPacket_destructor "_ZN10TextPacketD1Ev"